services:
  - type: web
    name: n8n-agent
    env: docker
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: kartik
      - key: N8N_BASIC_AUTH_PASSWORD
        value: StrongP@ss123
